# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem "mysql2"
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  primary:
    <<: *default
    database: multi_site_platform_development
  primary_replica:
    <<: *default
    database: multi_site_platform_development
    username: root_readonly
    replica: true
  primary_seller:
    <<: *default
    database: multi_site_platform_development_seller
    migrations_paths: db/sellers_migrations
  primary_seller_replica:
    <<: *default
    database: multi_site_platform_development_seller
    username: root_readonly
    replica: true
  primary_buyer:
    <<: *default
    database: multi_site_platform_development_buyer
    migrations_paths: db/buyers_migrations
  primary_buyer_replica:
    <<: *default
    database: multi_site_platform_development_buyer
    username: root_readonly
    replica: true

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  primary:
    <<: *default
    database: multi_site_platform_test
  primary_replica:
    <<: *default
    database: multi_site_platform_test
    username: root_readonly
    replica: true
  primary_seller:
    <<: *default
    database: multi_site_platform_test_seller
    migrations_paths: db/sellers_migrations
  primary_seller_replica:
    <<: *default
    database: multi_site_platform_test_seller
    username: root_readonly
    replica: true
  primary_buyer:
    <<: *default
    database: multi_site_platform_test_buyer
    migrations_paths: db/buyers_migrations
  primary_buyer_replica:
    <<: *default
    database: multi_site_platform_test_buyer
    username: root_readonly
    replica: true

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="mysql2://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values provided in this file. Alternatively, you can specify a connection
# URL environment variable explicitly:
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  <<: *default
  primary:
    <<: *default
    database: multi_site_platform_production
    username: multi_site_platform
    password: <%= ENV["MULTI_SITE_PLATFORM_DATABASE_PRODUCTION_PASSWORD"] %>
  primary_replica:
    <<: *default
    database: multi_site_platform_production
    username: multi_site_platform_readonly
    password: <%= ENV["MULTI_SITE_PLATFORM_DATABASE_PRODUCTION_READONLY_PASSWORD"] %>
    replica: true
  primary_seller:
    <<: *default
    database: multi_site_platform_production_seller
    username: multi_site_platform
    password: <%= ENV["MULTI_SITE_PLATFORM_DATABASE_PRODUCTION_PASSWORD"] %>
    migrations_paths: db/sellers_migrations
  primary_seller_replica:
    <<: *default
    database: multi_site_platform_production_seller
    username: multi_site_platform_readonly
    password: <%= ENV["MULTI_SITE_PLATFORM_DATABASE_PRODUCTION_READONLY_PASSWORD"] %>
    username: root_readonly
    replica: true
  primary_buyer:
    <<: *default
    database: multi_site_platform_production_buyer
    username: multi_site_platform
    password: <%= ENV["MULTI_SITE_PLATFORM_DATABASE_PRODUCTION_PASSWORD"] %>
    migrations_paths: db/buyers_migrations
  primary_buyer_replica:
    <<: *default
    database: multi_site_platform_production_buyer
    username: multi_site_platform_readonly
    password: <%= ENV["MULTI_SITE_PLATFORM_DATABASE_PRODUCTION_READONLY_PASSWORD"] %>
    username: root_readonly
    replica: true